### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by hotDOGEEE** [sigmaSd/bandito#1]
i want run start

**Comment by sigmaSd** [comment]
1- compile this crate https://github.com/sigmaSd/Eltrafico/tree/master/crates/eltrafico-tc
2- clone this repo
3- run in bash `MONITOR=bandwhich TC=path_to_the_compiled_binary_from_above  deno run -A --unstable main.ts wlan0`
4- now open localhost:8000 in your browser

That should be it

You need https://github.com/imsnif/bandwhich installed, if not you need to remove this part `MONITOR=bandwhich`
Also replace wlan0 with your actual network interface

**Comment by sigmaSd** [comment]
I added an appimage that is created with each commit from the ci, https://github.com/sigmaSd/bandito/releases

you can test it and report any issues

**Comment by sigmaSd** [comment]
Maybe this is easier https://github.com/sigmaSd/bandito-gtk
